name: Join team

on:
  workflow_dispatch:            # manual trigger, no inputs

jobs:
  join-team:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install --quiet requests

      # Optional: print which account the token belongs to
      - name: Show token owner (debug)
        env:
          LEAVE: ${{ secrets.LEAVE }}
        run: |
          echo "Token owner info:"
          curl -s -H "Authorization: Bearer $LEAVE" https://lichess.org/api/account | jq '.id, .username'

      - name: Join the team
        env:
          LEAVE:     ${{ secrets.LEAVE }}        # required token
          TEAM_PASS: ${{ secrets.TEAM_PASS }}    # optional password
          # TEAM_MSG can be set here if you want a custom message
        run: python join_team.py
