name: Join team

on:
  workflow_dispatch:  # Manual trigger only, no inputs

jobs:
  join-team:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install --quiet requests

      - name: Join the team
        env:
          TEAM: ${{ secrets.TEAM }}   # Your Lichess token
        run: |
          python join_team.py
