name: Join team

on:
  workflow_dispatch:              # run manually from the Actions tab
    inputs:
      message:
        description: "Optional join message shown to team admins"
        required: false
        default: "Hi, please add me!"

jobs:
  join-team:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install --quiet requests

      - name: Join the team
        env:
          TEAM: ${{ secrets.TEAM }}   # ← your token lives here (no quotes)
        run: |
          python join_team.py "${{ github.event.inputs.message }}"
