name: Leave  tournament

on:
  workflow_dispatch:       # run manually from the Actions tab

jobs:
  leave:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install --quiet requests

      - name: Withdraw from tournament
        env:
          LEAVE: ${{ secrets.LEAVE }}   # ← your token, no quotes
        run: python leave_tournament.py
